# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6bbbc6b0498f381b3925c57e7dd25ad2ca3b989897a70a8ba9487792c1d2e9ec7e1d6c905ebc48486c833862671992156186cfe9da831a59315d6bf8bf93135

test:
  secret_key_base: 2e14b751f8a5ae6a096a76db5a41baa6348ab7452f7ac4ca6f51bd5a3763b2950bd0dc3ad9a5803f1d48a263d22a39ba2d62f4c89c2684940a8b7e7b10dff937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
